[build]
  command = "npm --workspace frontend run build"
  publish = "frontend/dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- frontend assets package.json package-lock.json netlify.toml"
